package com.androiddevelopers.villabuluyorum.model.villa

data class Villa(
    var villaId: String? = null,
    var hostId: String? = null,
    var villaName: String? = null,
    var description: String? = null,
    var location: String? = null,
    var nightlyRate: Double? = null,
    var capacity: Int? = null,
    var bedroomCount: Int? = null,
    var bedCount: Int? = null,
    var bathroomCount: Int? = null,
    var restroom: Int? = null,
    var hasPool: Boolean? = null,
    var gardenArea: Double? = null,
    var interiorDesign: String? = null,
    var isQuietArea: Boolean? = null,
    var amenities: List<String>? = null,
    var minStayDuration: Int? = null,
    var reservationFee: Double? = null,
    var airbnbServiceFee: Double? = null,
    var totalExcludingTaxes: Double? = null,
    var region: String? = null,
    var attractions: List<String>? = null,
    var facilities: Facilities? = null,
    var price: Double? = null,
    var currency: String? = null,
)